name: Python CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with coverage
        run: |
          python -m coverage run -m pytest -q
          python -m coverage report --fail-under=85
          python -m coverage html
          coverage-badge -o coverage.svg -f
      - name: Generate coverage report
        run: |
          pip install coverage genbadge[coverage]
          coverage run -m pytest
          coverage xml
          genbadge coverage -i coverage.xml -o coverage.svg

      - name: Commit badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add coverage.svg
          git commit -m "chore: update coverage badge [skip ci]" || echo "No changes"
          git push

